variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - check
  - build
  - deploy

before_script:
  - node --version
  - npm install

prettier:
  stage: check
  image: node:12
  script:
    - npm run lint

jest:
  stage: check
  image: node:12
  script:
    - npm run test

build_all:
  stage: build
  image: node:12
  script:
    - npm run build:all

deploy_npm:
  stage: deploy
  image: node:12
  only:
    - tags
    - triggers
  script:
    - npm run build:all
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm publish
