variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - dist/
    - proto/
    - docs/

stages:
  - check
  - build
  - deploy

before_script:
  - node --version
  - npm install

prettier:
  stage: check
  image: node:12
  script:
    - npm run lint

jest:
  stage: check
  image: node:12
  script:
    - npm run test

build_all:
  stage: build
  image: node:12
  script:
    - npm run build:all

deploy_npm:
  stage: deploy
  image: node:12
  only:
    - tags
    - triggers
  script:
    - npm run build:all
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
    - npm publish


deploy_docs:
  stage: deploy
  image: registry.gitlab.com/matrixai/engineering/maintenance/gitlab-runner
  before_script:
    - git config user.email "robert.cronin@matrix.ai"
    - git config user.name "ci-build"
  # only:
  #   - tags
  #   - triggers
  script:
    - typedoc --out temp_docs
    - gh-pages --dist temp_docs
